- name: Create 2G swapfile
  become: yes
  command: fallocate -l 2G /swapfile

- name: Set permissions on swapfile
  become: yes
  file:
    path: /swapfile
    mode: '0600'

- name: Make swap file
  become: yes
  command: mkswap /swapfile

- name: Turn on swap
  become: yes
  command: swapon /swapfile

- name: Add to fstab
  become: yes
  lineinfile:
    dest: /etc/fstab
    regexp: /swapfile
    line: /swapfile none swap sw 0 0
