- name: Update apt packages
  become: yes
  apt:
    update_cache: yes

- name: Install gnupg
  become: yes
  apt:
    name: gnupg
    state: latest

- name: Add mongodb apt key
  become: yes
  shell: wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -

- name: Add mongodb source
  become: yes
  shell: echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list

- name: Update apt packages
  become: yes
  apt:
    update_cache: yes

- name: Install mongodb
  become: yes
  apt:
    name: mongodb-org
    state: latest

- name: Restart mongodb
  become: yes
  service:
    name: mongod
    state: restarted
    enabled: yes
