- name: Update apt packages
  become: yes
  apt:
    update_cache: yes

- name: Install nginx
  become: yes
  apt:
    name: nginx
    state: latest

- name: Turn off server tokens
  become: yes
  replace:
    path: /etc/nginx/nginx.conf
    regexp: '#\s*(server_tokens off;)'
    replace: '\1'

- name: Enable gzip
  become: yes
  replace:
    path: /etc/nginx/nginx.conf
    regexp: '#\s*(gzip_vary on;)'
    replace: '\1'

- name: Set gzip mime-type
  become: yes
  replace:
    path: /etc/nginx/nginx.conf
    regexp: '#\s*(gzip_types)'
    replace: '\1'

- name: Copy nginx configuration
  become: yes
  template:
    owner: root
    group: root
    mode: 0644
    src: chat
    dest: /etc/nginx/sites-available/chat

- name: Create a symbolic link to chat
  become: yes
  file:
    src: /etc/nginx/sites-available/chat
    dest: /etc/nginx/sites-enabled/chat
    owner: root
    group: root
    state: link

- name: Disable default site
  become: yes
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Restart nginx
  become: yes
  service:
    name: nginx
    state: restarted
    enabled: yes
